### ISSUE TITLE
phoneUtil.getRegionCodeForNumber make error

### ISSUE THREAD

**Issue by Dexus** [wajatimur/node-phonenumber#14]
```
node_modules\node-phonenumber\lib\libphonenumber\javascript\i18n\phonenumbers\phonenumberutil.js:2858
  var countryCode = number.getCountryCodeOrDefault();
                           ^

TypeError: number.getCountryCodeOrDefault is not a function
    at i18n.phonenumbers.PhoneNumberUtil.getRegionCodeForNumber (...\node_modules\node-phonenumber\lib\libphonenumber\javascript\i18n\phonenumbers\phonenumberutil.js:2858:28)
    at Object.<anonymous> (...\index2.js:79:33)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:445:3
```

**Comment by wajatimur** [comment]
Will check on the latest Google LibPhonenumber,

**Comment by wajatimur** [comment]
Can you try with the latest version?

**Comment by blerest** [comment]
same issue here with the latest version
